### PR TITLE
Issue #6 solved

### PR DESCRIPTION
**Pull request by Python-is-better-than-Java**
The function has been found but changes have to be made. Need more time.

### CODE REVIEW

**Comment by Python-is-better-than-Java** [comment]
Need more time

**Comment by Python-is-better-than-Java** [comment]
The issue has been solved.
The user can draw his own map by dragging the mouse across the map and click the mouse when done.

**Comment by Python-is-better-than-Java** [comment]
Now clicking implemented.

**Comment by Vaarun-C** [comment]
Its beautiful :). Currently its worth 40 points.

- +5 for making it a circle instead of a box
- +15 for trying out techniques like linear interpolation for filling in the gaps during fast cursor movement.
image

**Comment by Vaarun-C** [comment]
@Python-is-better-than-Java

**Comment by Python-is-better-than-Java** [comment]
I have tried resolving the gap issue to the best of my abilities.
Circles have been implemented instead of rectangles.

**Comment by Vaarun-C** [comment]
Perfect!!! :)

**Comment by Python-is-better-than-Java** [comment]
Thank you

**Pull request merged**
