### PR TITLE
Made changes on the issue#3

### PR DESCRIPTION
**Pull request by Acc0LadE**
Increased readability, reduced redundant code using functions, taking user input to make the code dynamic #3

### CODE REVIEW

**Comment by Vaarun-C** [comment]
- Can you be a little more specific with the comments
- The random generation functions are still left unaltered in NEAT.py. Again you only need to concentrate on NEAT.py for this issue.
- The code still looks convoluted

**Comment by Vaarun-C** [comment]
Only NEAT.py needs to be Refactored.

Please provide comments and function documentation("docstrings") amongst other things

HINT: Focus on Refactoring the mutation function and providing comments for each step

As of this instance, only 10-15 points can be granted

**Comment by Acc0LadE** [comment]
ok cool, i will be happy to be granted the 10-15points offered.
thanks

**Comment by Vaarun-C** [comment]
!bounty 10

**Pull request merged**
