### PR TITLE
Issue #4 fixed

### PR DESCRIPTION
**Pull request by Saahith1204**
Fixed the AttributeError that appear on trying to add a player car.
-Added a fitness variable initialized to 0 in class Player
-Appended an ID value of 0 to the player car

### CODE REVIEW

**Comment by Vaarun-C** [comment]
ok @Saahith1204 this is a working solution. I agree. But don't you think having a fitness attribute for Player object feels wrong?

**Comment by Vaarun-C** [comment]
If you can solve this without having a fitness attribute in Player() I can give you 20. Otherwise I can give you 5-10

**Comment by Vaarun-C** [comment]
just look into this @Saahith1204

**Comment by Saahith1204** [comment]
I agree it didn't make sense. Will look into it

**Comment by Saahith1204** [comment]
Also I request for re-assignment of this issue

**Comment by Vaarun-C** [comment]
Can you look into "isInstance()"? Also please check the if condition

**Comment by Saahith1204** [comment]
Okay can work with isInstance().

**Comment by Saahith1204** [comment]
These are all the commits that I shall be contributing. Please de-assign this issue from me. Thank you

**Comment by Vaarun-C** [comment]
Can you revert those 2 commits? I'll merge then @Saahith1204

**Comment by Saahith1204** [comment]
Will do.

**Comment by Saahith1204** [comment]
I've reverted the changes made in the previous 2 commits. The file should be in the state it was in after the first commit.

**Comment by Vaarun-C** [comment]
!bounty 7

**Pull request merged**
